service: nern-auth

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 30
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  signup:
    handler: auth/signup.handler
    events:
      - http:
          path: signup
          method: post
  login:
    handler: auth/login.handler
    events:
      - http:
          path: login
          method: post
  logout:
    handler: auth/logout.handler
    events:
      - http:
          path: login
          method: get

  authorizer:
    handler: auth/authorizer.handler
  greetings:
    handler: pages/greetings.handler
    events:
      - http:
          path: greetings
          method: get
          authorizer: ${self:custom.authorizer}

resources:
  Resources:
    sessionTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: sessions
        AttributeDefinitions:
          - AttributeName: session
            AttributeType: S
        KeySchema:
          - AttributeName: session
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    userTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-prune-plugin
custom:
  authorizer:
    name: authorizer
    identitySource: method.request.header.Cookie
    type: REQUEST
  prune:
    automatic: true
    number: 2
